---

# We now include mit.zabbix-agent.common via dependency in meta/main.yml
# This provides handlers like "Restart zabbix-agent" and vars like "zabbix_agent_conf_dir"

# not available in Debian 11 - see #19596
- name: Install python-reconfigure
  apt:
    pkg: python3-reconfigure
  #when: (ansible_distribution == "Debian" and ansible_distribution_major_version|int < 11)

- name: Copy zabbix-lld-https-sites
  copy:
    src: "{{ item }}"
    dest: /usr/local/bin/
    mode: 0755
  with_items:
    - zabbix-lld-https-sites
    - zabbix_lld_https_sites_mitnginxparser.py  

- name: Add zabbix-agent configuration file
  copy:
    src: local-userparameter_https-sites.conf
    dest: "{{ zabbix_agent_conf_dir }}"
    mode: 0644
  notify: Restart zabbix-agent

- name: Remove deprecated scripts from sbin
  file:
    path: "/usr/local/sbin/{{ item }}"
    state: absent
  with_items:
    - zabbix-lld-https-sites
    - zabbix_lld_https_sites_mitnginxparser.py

