---

# We now include mit.zabbix-agent.common via dependency in meta/main.yml
# This provides handlers like "Restart zabbix-agent" and vars like "zabbix_agent_conf_dir"

- name: Copy requirements.txt
  copy:
    src: requirements.txt
    dest: /opt/mit-zabbix-lld-https-sites/

- name: Install python3-venv
  apt:
    pkg: python3-venv

- name: Install pip in venv
  pip:
    name: pip
    virtualenv: /opt/mit-zabbix-lld-https-sites/.venv
    virtualenv_command: python3 -m venv

- name: Updated python dependencies (requirements.txt)
  pip:
    virtualenv_command: python3 -m venv
    requirements: /opt/mit-zabbix-lld-https-sites/requirements.txt
    virtualenv: /opt/mit-zabbix-lld-https-sites/.venv
  environment: "{{ proxy_env }}"

- name: Copy zabbix-lld-https-sites
  copy:
    src: "{{ item }}"
    dest: /opt/mit-zabbix-lld-https-sites/bin/
    mode: 0755
  with_items:
    - zabbix-lld-https-sites
    - zabbix_lld_https_sites_mitnginxparser.py  

- name: Add zabbix-agent configuration file
  copy:
    src: local-userparameter_https-sites.conf
    dest: "{{ zabbix_agent_conf_dir }}"
    mode: 0644
  notify: Restart zabbix-agent

- name: Remove deprecated scripts
  file:
    path: "/usr/local/{{ item }}"
    state: absent
  with_items:
    - bin/zabbix-lld-https-sites
    - bin/zabbix_lld_https_sites_mitnginxparser.py
    - sbin/zabbix-lld-https-sites
    - sbin/zabbix_lld_https_sites_mitnginxparser.py

