#!/opt/mit-zabbix-lld-https-sites/.venv/bin/python
#
# Distributed via ansible - mit.zabbix-agent.https-sites
#
# v2022-04-19 by markus.meissner@meissner.IT

# https://www.askpython.com/python/python-command-line-arguments
import argparse
import csv
import json
import glob
import os

from reconfigure.parsers import *
from reconfigure.includers import *

from zabbix_lld_https_sites_mitnginxparser import MitNginxParser

parser = argparse.ArgumentParser()
# https://stackoverflow.com/questions/15008758/parsing-boolean-values-with-argparse#comment74363171_15008758
parser.add_argument('--include-http', dest='include_http', default=False, action='store_true')
args = parser.parse_args()

data = list()

# Nginx
parser = MitNginxParser()
for filename in glob.iglob('/etc/nginx/conf.d/server-*.conf'):
    nodes = parser.parse(open(filename).read())
    #print nodes

    for server in nodes.get_all('server'):
        if args.include_http or "443" in server.get('listen').value.split():
            for site in server.get('server_name').value.split():
                data.append({"{#HTTPSSITE}": site, "{#HTTPSPORT}": 443, "{#HTTPSSITENAME}": site})

# Apache
import re
serverNames = set()
for filename in glob.iglob('/etc/apache2/sites-enabled/*.conf'):
    for line in open(filename, 'r'):
        serverName = re.search( r'^[ \t]+ServerName (.*)', line, re.M|re.I)
        if serverName:
            serverNames.add(serverName.group(1))
        # We don't collect ServerAlias or http hosts as there are none at Monheim
for serverName in serverNames:
    data.append({"{#HTTPSSITE}": serverName, "{#HTTPSPORT}": 443, "{#HTTPSSITENAME}": serverName})

# Custom
conffile = '/etc/zabbix/mit-zabbix-lld-https-sites.conf'
if os.path.exists(conffile):
    with open(conffile) as csvfile:
        csvreader = csv.reader(csvfile)
        for row in csvreader:
            data.append({"{#HTTPSSITE}": row[0], "{#HTTPSPORT}": row[1], "{#HTTPSSITENAME}": row[2]})

# Output all
print(json.dumps({"data": data}, indent=4))

